### PR TITLE
fix atom:Path string size while loading ir

### LINKED ISSUE #9: Corrupted path when loading some IR files randomly
Example log:
```
ZConvolv Convolver: Error: cannot open IR file.
ZConvolv Load: configuration failed for ir '/home/myrrc/music/lib/ir/airwindows/PrimeMed.flacc'.
ZConvolv Convolver: Error: cannot open IR file.
ZConvolv Load: configuration failed for ir '/home/myrrc/music/lib/ir/airwindows/PlateMedium.flacP'.
ZConvolv Convolver: Error: cannot open IR file.
ZConvolv Load: configuration failed for ir '/home/myrrc/music/lib/ir/airwindows/PrimeMed.flacll.flac'.
```

### PR DESCRIPTION
**Pull request by myrrc**
Resolves: #9

### CODE REVIEW

**Comment by x42** [comment]
That should not be needed the path passed by the host should be NULL terminated.

This is already the case for state

https://github.com/x42/zconvo.lv2/blob/ec2ff40b5f9701fdc2e3944657f3737b89be4b18/src/lv2.cc#L744

and internal messaging:

https://github.com/x42/zconvo.lv2/blob/ec2ff40b5f9701fdc2e3944657f3737b89be4b18/src/lv2.cc#L886-L892

Note `1 + strlen (path)`.

Besides this is is POD payload. So the host is expected to return all the bytes as-is, and it seems here the last byte is missing.
If this was not a NULL terminated string, but other raw data that can lead to corrupt state..

I'l see if I can get Justin on the horn.

--
PS. I'll merge it once we get to the bottom of the issue in Reaper. Chances are that other plugins are affected  as well, and it'll be worse for C plugins using char* that expect a NULL termination.

**Comment by x42** [comment]
I just got confirmation:

> Ah thank you, REAPER is not NULL terminating its atom#Path, fixing!
>
> Justin

**Comment by x42** [comment]
I've merged it in v0.7.1-1 1fcbfc5, since the change does not hurt.

Yet, if you could confirm the fix in REAPER, using the old version of the plugin that'll be appreciated.

Thank you!

**Comment by myrrc** [comment]
Good day Robin,

I've tested old version on Reaper v7.28 (with path fix) and confirm it works.
I'd advice not to revert the change as there may be other hosts not null-terminating
the string (afaik lv2 standard doesn't mandate that?)

-- 
Mikhail :з

**Comment by x42** [comment]
A http://lv2plug.in/ns/ext/atom#Path is-a http://lv2plug.in/ns/ext/atom#String which is to be terminated with a NULL byte ('\0') according to the spec.

**Pull request closed without merging**
